---
- hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansible-rg
        location: eastus
        tags:
            testing: testing
            delete: never
      register: rg
    - debug:
        var: rg
